import json
import httpx
from fastapi import FastAPI, Request, status
import uvicorn

app = FastAPI(title="⚡ AI Telemetry Log Analyzer")

OLLAMA_HOST = "http://localhost:11434"
MODEL_NAME = "qwen2.5-coder:7b"

def audit_log_with_llm(log_message: str, service_name: str) -> str:
    prompt = f"""You are an SRE Auto-Healing Agent.
    Analyze the following error log generated by the service: '{service_name}'.
    
    Log Payload:
    "{log_message}"
    
    Provide:
    1. A 1-sentence plain English explanation of the root cause.
    2. The exact commands (kubectl or bash) to debug and resolve this issue.
    
    Output format: Keep it highly structured and technical.
    """
    
    try:
        payload = {
            "model": MODEL_NAME,
            "prompt": prompt,
            "stream": False
        }
        response = httpx.post(f"{OLLAMA_HOST}/api/generate", json=payload, timeout=30.0)
        if response.status_code == 200:
            return response.json()["response"].strip()
        return "Error querying local model."
    except Exception as e:
        # Fallback simulation if local LLM is offline
        return f"""⚠️ [Simulation Mode] Telemetry analyzer received log event from '{service_name}'.
        
        Analyzed log string: "{log_message}"
        
        Possible Cause: Container exceeded allotted resource limits or crashed on library setup.
        Recommended Remediation:
        - Check pod resource allocations: 'kubectl describe pod -l app={service_name}'
        - Restart deployment: 'kubectl rollout restart deployment/{service_name}'"""

@app.post("/logs")
async def receive_logs(request: Request):
    """Listens for logs piped from Vector.dev routing loops."""
    payload = await request.json()
    
    # 1. Parse standard syslog properties
    log_message = payload.get("message", "")
    service_name = payload.get("service", "unknown-service")
    severity = payload.get("severity", "info").upper()
    
    print(f"\n📥 Received log stream from '{service_name}' [Severity: {severity}]")
    
    # 2. Filter: Process only WARNING, ERROR, or CRITICAL states
    if severity in ["WARNING", "ERROR", "CRITICAL", "FATAL"]:
        print(f"🚨 Anomalous log detected! Commencing AI diagnostics...")
        
        # In production, check inputs through safety scanners before LLM compilation
        diagnosis = audit_log_with_llm(log_message, service_name)
        
        print("\n🏆 AI Diagnostician Resolution Manual:")
        print(diagnosis)
        
        # Here, you can trigger webhooks to forward the diagnosis to Slack or Alertmanager
        return {"status": "analyzed", "diagnosis": diagnosis}
        
    return {"status": "ignored", "reason": "Severity below threat threshold."}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8383)
